export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fdf9f2',
        'surface-bright': '#fdf9f2',
        'surface-dim': '#dddad3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ec',
        'surface-container': '#f1ede6',
        'surface-container-high': '#ebe8e1',
        'surface-container-highest': '#e6e2db',
        'surface-variant': '#e6e2db',
        'surface-tint': '#4e5e81',
        background: '#fdf9f2',
        'on-background': '#1c1c18',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#31302c',
        'inverse-on-surface': '#f4f0e9',
        'inverse-primary': '#b6c6ee',
        primary: '#000516',
        'on-primary': '#ffffff',
        'primary-container': '#0b1e3d',
        'on-primary-container': '#7686ab',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#b6c6ee',
        'on-primary-fixed': '#071b3a',
        'on-primary-fixed-variant': '#364768',
        secondary: '#795902',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdd275',
        'on-secondary-container': '#775800',
        'secondary-fixed': '#ffdf9e',
        'secondary-fixed-dim': '#ebc166',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5b4300',
        tertiary: '#000702',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002412',
        'on-tertiary-container': '#2c9863',
        'tertiary-fixed': '#90f7ba',
        'tertiary-fixed-dim': '#74db9f',
        'on-tertiary-fixed': '#002110',
        'on-tertiary-fixed-variant': '#005230',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#75777f',
        'outline-variant': '#c5c6cf',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-lg': ['Inter'],
        'display-hero': ['Montserrat'],
        'display-hero-mobile': ['Montserrat'],
        'headline-sm': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'headline-xl': ['Montserrat'],
        'headline-xl-mobile': ['Montserrat'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-lg': ['15px', { lineHeight: '20px', fontWeight: '500' }],
        'display-hero': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', fontWeight: '600' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
