# Generated by Django 5.2.17 on 2026-09-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_national_id_required', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_countr_slug_8790d7_idx'), models.Index(fields=['is_active', 'is_national_id_required'], name='core_countr_is_acti_7e1857_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('duration_days', models.IntegerField()),
                ('entry_type', models.CharField(choices=[('single', 'Single Entry'), ('multiple', 'Multiple Entry')], max_length=20)),
                ('category', models.CharField(choices=[('tourist', 'Tourist'), ('transit', 'Transit'), ('job_seeker', 'Job Seeker'), ('freelance', 'Freelance')], max_length=20)),
                ('processing_time', models.CharField(max_length=100)),
                ('visa_validity', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_visaty_slug_ac5d03_idx'), models.Index(fields=['category', 'is_active'], name='core_visaty_categor_21c20b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('citizen_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='core.country')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='core.visatype')),
            ],
            options={
                'indexes': [models.Index(fields=['visa_type', 'citizen_country'], name='core_pricin_visa_ty_800bcd_idx')],
                'unique_together': {('visa_type', 'citizen_country')},
            },
        ),
    ]
