# Generated by Django 5.2.17 on 2026-09-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_alter_country_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricing',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Leave empty for base price regardless of destination.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='core.destination'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='travelling_from_country',
            field=models.ForeignKey(blank=True, help_text='Leave empty for base price regardless of departure country.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings_as_from', to='core.country'),
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('visa_type', 'citizen_country', 'travelling_from_country', 'destination')},
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['visa_type', 'citizen_country', 'travelling_from_country', 'destination'], name='core_pricin_visa_ty_c64f2a_idx'),
        ),
    ]
