# Generated by Django 5.2.17 on 2026-09-25 17:42
# NOTE (prod Supabase): the core_pricing table was originally created by hand
# via supabase_schema.sql, which made a UNIQUE *INDEX* named
# core_pricin_visa_ty_unique instead of a real constraint. A plain
# AlterUniqueTogether fails there because there is no constraint to drop.
# So the constraint swap below is done with IF EXISTS-safe raw SQL.
# Fresh databases created purely by migrations are unaffected in state.
# (Local SQLite dev DBs already applied the original version of this
# migration; the raw SQL below is Postgres-specific and only matters for
# databases that were hand-built from supabase_schema.sql.)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_alter_country_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricing',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Leave empty for base price regardless of destination.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='core.destination'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='travelling_from_country',
            field=models.ForeignKey(blank=True, help_text='Leave empty for base price regardless of departure country.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings_as_from', to='core.country'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='pricing',
                    unique_together={('visa_type', 'citizen_country', 'travelling_from_country', 'destination')},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS core_pricin_visa_ty_unique;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE core_pricing DROP CONSTRAINT IF EXISTS core_pricin_visa_ty_unique;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE core_pricing ADD CONSTRAINT core_pricing_4field_uniq UNIQUE (visa_type_id, citizen_country_id, travelling_from_country_id, destination_id);',
                    reverse_sql='ALTER TABLE core_pricing DROP CONSTRAINT IF EXISTS core_pricing_4field_uniq;',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['visa_type', 'citizen_country', 'travelling_from_country', 'destination'], name='core_pricin_visa_ty_c64f2a_idx'),
        ),
    ]
