# Generated by Django 5.2.17 on 2026-09-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('core', '0002_destination_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.destination'),
        ),
    ]
