# Generated by Django 5.2.17 on 2026-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='national_id_file',
            field=models.FileField(blank=True, null=True, upload_to='national_ids/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
