# Generated by Django 5.2.17 on 2026-09-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentIntent',
        ),
    ]
